# Generated by Django 4.2.1 on 2023-07-05 08:01

import common.utils
from django.db import migrations, models
import django.db.models.deletion
import fiscalyear.utils
import product.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyinfo', '0001_initial'),
        ('accounting', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=10, validators=[fiscalyear.utils.validate_fiscal_year])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=15)),
                ('tax_status', models.CharField(choices=[('taxable', 'Taxable'), ('non_taxable', 'Non Taxable')], default='taxable', max_length=24)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyinfo.companyinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=10, validators=[fiscalyear.utils.validate_fiscal_year])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyinfo.companyinfo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_ingredients', to='inventory.inventoryitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='product.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.substore')),
            ],
            options={
                'verbose_name': 'product ingredient',
                'verbose_name_plural': 'product ingredients',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.utils.get_product_image_upload_folder, validators=[common.utils.image_validate])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyinfo.companyinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=10, validators=[fiscalyear.utils.validate_fiscal_year])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=15)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyinfo.companyinfo')),
            ],
            options={
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='product.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_discount_rule', to='accounting.discountrule'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product', to='product.productimage'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_tax_rule', to='accounting.taxrule'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.measurementunit'),
        ),
    ]
