# Generated by Django 4.2.1 on 2023-07-05 08:01

import common.utils
from django.db import migrations, models
import django.db.models.deletion
import room.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('companyinfo', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyinfo.companyinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyinfo.companyinfo')),
            ],
            options={
                'verbose_name_plural': 'room categories',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=room.utils.get_upload_folder, validators=[common.utils.image_validate])),
                ('floor', models.CharField(max_length=50)),
                ('room_status', models.CharField(choices=[('free', 'Free'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='free', max_length=15)),
                ('room_capacity', models.PositiveIntegerField()),
                ('include_breakfast', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyinfo.companyinfo')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='room.roomcategory')),
                ('room_features', models.ManyToManyField(to='room.roomfeature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField()),
                ('extended_time', models.DateTimeField(blank=True, null=True)),
                ('extended_period', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True)),
                ('adult', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyinfo.companyinfo')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='customer.customer')),
                ('discount_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_discount_rule', to='accounting.discountrule')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.room')),
                ('tax_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_tax_rule', to='accounting.taxrule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
