# Generated by Django 4.2.1 on 2023-07-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedroom',
            name='room',
        ),
        migrations.AddField(
            model_name='bookedroom',
            name='room',
            field=models.ManyToManyField(related_name='booked_rooms', to='room.room'),
        ),
    ]
