# Generated by Django 4.2.1 on 2023-07-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_bookedroom_room_bookedroom_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedroom',
            old_name='room',
            new_name='rooms',
        ),
    ]
