# Generated by Django 4.2.1 on 2023-07-05 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fiscalyear', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('device_limit', models.IntegerField(default=1)),
                ('branch_limit', models.IntegerField(default=1)),
                ('duration', models.PositiveIntegerField(default=1)),
                ('period_type', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default=('year', 'Year'), max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='subscription.subscriptionplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=150)),
                ('is_maintainance', models.BooleanField(default=False)),
                ('device_limit', models.PositiveIntegerField(default=1)),
                ('device_count', models.PositiveIntegerField(default=0)),
                ('branch_limit', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('expiry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='auth.group')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DevicesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50, null=True)),
                ('device_type', models.CharField(max_length=50)),
                ('device_os', models.CharField(max_length=50)),
                ('browser_type', models.CharField(max_length=50)),
                ('device_user', models.CharField(max_length=50)),
                ('refresh_token', models.TextField()),
                ('is_active', models.BooleanField(default=1)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='fiscalyear.fiscalyear')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='subscription.subscription')),
            ],
            options={
                'verbose_name_plural': 'device histories',
            },
        ),
    ]
