# Generated by Django 4.2.1 on 2023-07-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=1000, unique=True)),
            ],
        ),
    ]
