# Generated by Django 4.2.1 on 2023-07-05 08:01

import common.utils
import companyinfo.utils
from django.db import migrations, models
import fiscalyear.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=10, validators=[fiscalyear.utils.validate_fiscal_year])),
                ('logo', models.ImageField(blank=True, null=True, upload_to=companyinfo.utils.get_upload_folder, validators=[common.utils.image_validate])),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('pan_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('tax', models.DecimalField(decimal_places=5, default=0.0, help_text='Specify in %', max_digits=30)),
                ('service_charge', models.DecimalField(decimal_places=5, default=0.0, max_digits=30)),
                ('currency', models.CharField(choices=[('NPR', 'NPR'), ('INR', 'INR'), ('USD', 'USD')], default='NPR', max_length=10)),
                ('is_company_vat_pan', models.CharField(choices=[('PAN', 'PAN'), ('VAT', 'VAT')], default='PAN', max_length=5)),
                ('cmbs_username', models.CharField(max_length=50)),
                ('cmbs_password', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('facebook_link', models.CharField(max_length=100, null=True)),
                ('instagram_link', models.CharField(max_length=100, null=True)),
                ('twitter_link', models.CharField(max_length=100, null=True)),
                ('linkedin_link', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'company info',
            },
        ),
    ]
