# Generated by Django 4.2.1 on 2023-07-05 08:01

import django.contrib.admin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomActionLogs',
            fields=[
                ('logentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin.logentry')),
                ('device_ip', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50, null=True)),
                ('device_type', models.CharField(max_length=50)),
                ('device_os', models.CharField(max_length=50)),
                ('browser_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ibs log',
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
