# Generated by Django 4.2.1 on 2023-07-05 08:01

import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fiscalyear.utils
import invoice.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0001_initial'),
        ('table', '0001_initial'),
        ('companyinfo', '0001_initial'),
        ('inventory', '0001_initial'),
        ('supplier', '0001_initial'),
        ('accounting', '0001_initial'),
        ('customer', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=10, validators=[fiscalyear.utils.validate_fiscal_year])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_date', models.DateTimeField()),
                ('ref_bill_no', models.CharField(max_length=50)),
                ('gross_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=16)),
                ('tax_vat_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=16)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=16)),
                ('net_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=16)),
                ('payment_mode', models.CharField(max_length=150)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyinfo.companyinfo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=10, validators=[fiscalyear.utils.validate_fiscal_year])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref_bill_no', models.CharField(max_length=50)),
                ('gross_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=16)),
                ('payment_mode', models.CharField(max_length=150)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=48)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyinfo.companyinfo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='customer.customer')),
                ('discount_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_room_discount_rule', to='accounting.discountrule')),
                ('items', models.ManyToManyField(related_name='checkout_invoice', to='product.product')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='room.bookedroom')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='table.table')),
                ('tax_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_room_tax_rule', to='accounting.taxrule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=10, validators=[fiscalyear.utils.validate_fiscal_year])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=4, max_digits=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyinfo.companyinfo')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.inventoryitem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoice_lines', to='invoice.purchaseinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=invoice.utils.get_purchase_invoice_image_upload_folder, validators=[common.utils.image_validate])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyinfo.companyinfo')),
            ],
            options={
                'verbose_name': 'Purchase Invoice Image',
                'verbose_name_plural': 'Purchase Invoicee Images',
            },
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='invoice_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_invoice', to='invoice.purchaseinvoiceimage'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supplier.supplier'),
        ),
    ]
