# Generated by Django 4.2.1 on 2023-07-05 08:01

from django.db import migrations, models
import django.db.models.deletion
import fiscalyear.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=10, validators=[fiscalyear.utils.validate_fiscal_year])),
                ('name', models.CharField(max_length=150)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate should be in percentage', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyinfo.companyinfo')),
            ],
            options={
                'verbose_name': 'tax rule',
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=10, validators=[fiscalyear.utils.validate_fiscal_year])),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyinfo.companyinfo')),
            ],
            options={
                'verbose_name': 'discount rule',
            },
        ),
    ]
