# Generated by Django 4.2.1 on 2023-07-05 10:30

from django.db import migrations, models
import django.db.models.deletion
import order.validator


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_bookedroom_room_bookedroom_room'),
        ('companyinfo', '0001_initial'),
        ('product', '0001_initial'),
        ('order', '0002_alter_roomorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomorder',
            name='products',
        ),
        migrations.RemoveField(
            model_name='roomorder',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='roomorder',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='room_orders', to='room.room'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[order.validator.validate_minimum])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='companyinfo.companyinfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='roomorder',
            name='order_items',
            field=models.ManyToManyField(related_name='order_items', to='order.orderitem'),
        ),
    ]
